### PR TITLE
fix: Fix K8s events query for JSON schema

### LINKED ISSUE #1327: kubernete dashboard not full work.Latest Kubernetes Warning Events have error info
first I opened json feature,I don't know whether there is an effect

error info

```text
First argument for function 'arrayElement' must be array, got 'JSON' instead: In scope SELECT Timestamp AS Timestamp, JSONExtractString(LogAttributes['object'], 'type') AS Severity, JSONExtractString(LogAttributes['object'], 'regarding', 'kind') AS Kind, JSONExtractString(LogAttributes['object'], 'regarding', 'name') AS Name, JSONExtractString(LogAttributes['object'], 'note') AS Message, Timestamp, ServiceName FROM default.otel_logs WHERE ((Timestamp >= fromUnixTimestamp64Milli(_CAST(1762343814887, 'Int64'))) AND (Timestamp <= fromUnixTimestamp64Milli(_CAST(1762347414887, 'Int64')))) AND ((toString(LogAttributes.k8s.resource.name) = 'events') AND (Severity != 'Normal')) ORDER BY Timestamp DESC LIMIT _CAST(0, 'Int32'), _CAST(200, 'Int32'). 
```

```sql
SELECT
  Timestamp AS "Timestamp",
  JSONExtractString (LogAttributes['object'], 'type') AS "Severity",
  JSONExtractString (LogAttributes['object'], 'regarding', 'kind') AS "Kind",
  JSONExtractString (LogAttributes['object'], 'regarding', 'name') AS "Name",
  JSONExtractString (LogAttributes['object'], 'note') AS "Message",
  Timestamp,
  ServiceName
FROM
  default.otel_logs
WHERE
  (
    Timestamp >= fromUnixTimestamp64Milli (1762343814887)
    AND Timestamp <= fromUnixTimestamp64Milli (1762347414887)
  )
  AND (
    (
      (
        (
          toString (`LogAttributes`.`k8s`.`resource`.`name`) = 'events'
        )
        AND (Severity != 'Normal')
      )
    )
  )
ORDER BY
  Timestamp DESC
LIMIT
  200
OFFSET
  0
```

### PR DESCRIPTION
**Pull request by pulpdrew**
Closes HDX-2738
Closes #1327

# Summary

This PR fixes the Kubernetes Warning Events table for JSON schemas.

## Before

JSON schema was broken

Screenshot 2026-01-14 at 2 49 05 PM

## After

Map-schema and JSON schema both work:

Screenshot 2026-01-14 at 2 00 10 PM
Screenshot 2026-01-14 at 1 59 59 PM

### CODE REVIEW

File: packages/app/src/KubernetesDashboardPage.tsx [hunk 1]
```diff
@@ -1168,27 +1169,48 @@ function KubernetesDashboardPage() {
...
+      },
+    );
+
+  const eventAttributeExpressions = useMemo(() => {
+    if (isLoadingJsonColumns || !logSource) {
+      return undefined;
+    }
+
+    if (
+      logSourceJsonColumns?.includes(logSource.eventAttributesExpression ?? '')
```
Comment (brandon-pereira) [inline packages/app/src/KubernetesDashboardPage.tsx]: Not seeing issues, but maybe 

`logSource && logSourceJsonColumns?.includes(logSource.eventAttributesExpression)` would be better? I am not sure if there's a scenario where `logSourceJsonColumns` contains `''` but that would break this

Comment (pulpdrew) [reply packages/app/src/KubernetesDashboardPage.tsx]: Yeah that's a good idea - updated to `logSource.eventAttributesExpression && logSourceJsonColumns?.includes(logSource.eventAttributesExpression)`
